# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('sexo', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Doctores',
                'verbose_name': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'verbose_name': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('sexo', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('facultad', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('vinculacion', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atencion.Consulta')),
                ('estatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('FC', models.IntegerField()),
                ('FR', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('orl', models.CharField(max_length=100)),
                ('piel_anexo', models.CharField(max_length=100)),
                ('ostio_muscular', models.CharField(max_length=100)),
                ('cabeza_cuello', models.CharField(max_length=100)),
                ('torax', models.CharField(max_length=100)),
                ('abdomen', models.CharField(max_length=100)),
                ('genito_urinario', models.CharField(max_length=100)),
                ('extremidades', models.CharField(max_length=100)),
                ('neurologico', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Examenes',
                'verbose_name': 'Examen',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together=set([('nombre', 'apellido', 'cedula')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Especialidad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Doctor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set([('doctor', 'paciente', 'fecha')]),
        ),
    ]
