# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_auto_20161005_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='conducta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='recomendaciones',
            field=models.TextField(),
        ),
    ]
