# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Facultad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Programa'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='vinculacion',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Funcionario', 'Funcionario'), ('Egresado', 'Egresado'), ('Visitante', 'Visitante')], max_length=12),
        ),
    ]
